const Map<String, List<String>> diseaseLabels = {
  'Rice': [
    'bacterial_leaf_blight',
    'brown_spot',
    'healthy',
    'leaf_blast',
    'leaf_scald',
    'narrow_brown_spot',
    'neck_blast',
    'rice_hispa',
    'sheath_blight',
    'tungro',
  ],
  'Sugarcane': ['Healthy', 'Mosaic', 'RedRot', 'Rust', 'Yellow'],
  'Groundnut': [
    'early_leaf_spot',
    'late_leaf_spot',
    'nutrition_deficiency',
    'rust',
    'healthy',
  ],
  'Cotton': ['Bacterial_blight', 'Curl_virus', 'Fusarium_wilt', 'Healthy'],
  'Corn': ['Blight', 'Common_Rust', 'Grey_leaf_spot', 'Healthy'],
  'Coconut': ['Bud Root Dropping', 'Bud Rot', 'Healthy', 'Leaf Rot', 'Grey Leafspot'],
  'Banana': ['Black Sigatoka', 'Cordana', 'Healthy' ,'Panama Disease', 'Yellow Sigatoka'],
  'Coffee': ['Healthy', 'Leaf_Rust', 'Cerscospora', 'Phoma'],
  'Wheat': ['Brown_Rust', 'Healthy', 'Septoria', 'Yellow_Rust'],
  'Tomato': ['Bacterial_spot', 'Early_blight', 'Late_blight', 'Leaf_Mold','Target_Spot', 'Healthy', 'Black_spot'],
};
