const Map<String, List<String>> diseaseLabels = {
  'Rice': [
    'bacterial_leaf_blight',
    'brown_spot',
    'healthy',
    'leaf_blast',
    'leaf_scald',
    'narrow_brown_spot',
    'neck_blast',
    'rice_hispa',
    'sheath_blight',
    'tungro',
  ],
  'Sugarcane': ['Healthy', 'Mosaic', 'RedRot', 'Rust', 'Yellow'],
  'Groundnut': [
    'alternaria_leaf_spot',
    'early_leaf_spot',
    'early_rust',
    'healthy_leaf',
    'late_leaf_spot',
    'nutrition_deficiency',
    'rust',
  ],
  'Cotton': ['Bacterial_blight', 'Curl_virus', 'Fusarium_wilt', 'Healthy'],
  'Corn': ['Blight', 'Common_Rust', 'Grey_leaf_spot', 'Healthy'],
  'Coconut': ['budrooting', 'budrot', 'healthy', 'leafrot', 'leafspot'],
  'Banana': ['Cordana', 'Healthy', 'Pestalotiopsis', 'Sigatoka'],
  'Coffee': ['Healthy', 'Leaf_Rust', 'Cerscospora', 'Phoma'],
  'Wheat': ['Healthy', 'Smut', 'Septoria', 'Brown_Rust','Yellow_Rust'],
  'Tomato': ['Bacterial_spot', 'Early_blight', 'Late_blight', 'Leaf_Mold','Target_Spot', 'Healthy', 'Black_spot'],
};
