name: agrhi
description: "Smart Farming Solutions - Offline-First Agricultural App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.5.0
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  image_picker: ^1.2.0
  open_meteo: ^2.1.8
  geolocator: ^12.0.0
  permission_handler: ^12.0.1
  geocoding: ^3.0.0
  google_mlkit_translation: ^0.13.0
  dio: ^5.9.0
  flutter_launcher_icons: ^0.14.4 
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/logo_nb.png
  android: true
  ios: true
  fullscreen: false

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/images/logo_nb.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_nb.png"
  
